var txtDic = {
    "Es": "Es",
    "undefined": "indefinido",
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "10",
    "11": "11",
    "12": "12",
    "13": "13",
    "14": "14",
    "15": "15",
    "16": "16",
    "17": "17",
    "18": "18",
    "19": "19",
    "20": "20",
    "21": "21",
    "22": "22",
    "23": "23",
    "24": "24",
    "25": "25",
    "26": "26",
    "27": "27",
    "28": "28",
    "29": "29",
    "30": "30",
    "35": "35",
    "40": "40",
    "45": "45",
    "50": "50",
    "55": "55",
    "2023": "2023",
    "": "",
    "Settings": "Ajustes",
    "×": "×",
    "Send a Review Invite": "Enviar una invitación para opinar",
    "Client Check In": "Registro de clientes",
    "Book a new appointment in calendar": "Reserve una nueva cita en el calendario",
    "MM": "MM",
    "23 de oct. de 2022 - 24 de abr. de 2023": "23 de oct. de 2022 - 24 de abr. de 2023",
    "Customer Name": "Nombre del cliente",
    "x": "X",
    "Marketing": "Marketing",
    "English": "Inglés",
    "Support": "Ayuda",
    "Add": "Agregar",
    "Close": "Cerrar",
    "Search": "Buscar",
    "Ignore": "Ignorar",
    "?": "?",
    "Cancel": "Cancelar",
    "mar.": "mar.",
    "Notifications": "Notificaciones",
    "Click here": "Haga clic aquí",
    "This week": "Esta semana",
    "Save": "Ahorrar",
    "Last 7 days": "Los últimos 7 días",
    "This year": "Este año",
    "Last year": "El año pasado",
    "Create an Appointment": "Crear una cita",
    "unknown": "desconocido",
    "This month": "Este mes",
    "Signout": "Desconectar",
    "Automation": "Automatización",
    "Login As": "Iniciar sesión como",
    "Calendars": "calendarios",
    "Contacts": "Contactos",
    "French": "Francés",
    "View Changelog": "Ver registro de cambios",
    "360 Adspy": "360 Adspy",
    "Send a review request to the customizer": "Enviar una solicitud de revisión al personalizador",
    "Portuguese (Portugal, Brazil)": "Portugués (Portugal, Brasil)",
    "Delete": "Borrar",
    "Create an Opportunity": "Crear una oportunidad",
    "to re-integrate.": "para reintegrarse.",
    "Help Center": "Centro de ayuda",
    "Tasks": "Tareas",
    "Send a Review Request": "Enviar una solicitud de revisión",
    "Ads Generator": "Generador de anuncios",
    "Resolve": "Resolver",
    "Select date & time": "Seleccione fecha",
    "Sites": "Sitios",
    "Italian": "Italiano",
    "Last week": "La semana pasada",
    "Polish": "Polaco",
    "vie.": "vie.",
    "Schedule appointment": "Programar una cita",
    "Add opportunity --": "Añadir oportunidad --",
    "Last 30 days": "últimos 30 días",
    "00:00:00": "00:00:00",
    "Spanish": "Español",
    "ctrl K": "ctrl k",
    "dom.": "dom.",
    "Customer email or phone": "Correo electrónico o teléfono del cliente",
    "German": "Alemán",
    "Dashboard": "Panel",
    "Reporting": "Informes",
    "Payments": "Pagos",
    "Conversations": "Conversaciones",
    "Add a Contact": "Añade un contacto",
    "Opportunities": "Oportunidades",
    "Switch to Agency View": "Cambiar a vista de agencia",
    "lun.": "lun.",
    "Privacy Mode": "Modo privado",
    "Translate": "Traducir",
    "Translate!": "¡Traducir!",
    "Last month": "El mes pasado",
    "Reputation": "Reputación",
    "Mickey Mouse": "Mickey Mouse",
    "There is a problem with the MailGun integration of 005 - Dentrika Onboarding.": "Hay un problema con la integración de MailGun de 005 - Dentrika Onboarding.",
    "mié.": "mié",
    "Add a new Contact from scratch": "Agregar un nuevo contacto desde cero",
    "lombardoalessandro25@hotmail.com": "lombardoalessandro25@hotmail.com",
    "005 - Dentrika Onboarding -- Mexico, CDMX": "005 - Dentrika Onboarding -- México, CDMX",
    "Phone configurations are missing for this account. Please contact agency": "Faltan configuraciones de teléfono para esta cuenta. Póngase en contacto con la agencia",
    "abril": "Abril",
    "$0.00": "$0.00",
    "Open": "Abierto",
    "Quick Actions": "Acciones rápidas",
    "Launchpad": "Lanzamiento",
    "2. YES > Proposal Sent": "2. SI > Propuesta Enviada",
    "Source": "Fuente",
    "Pipeline Value": "Valor de canalización",
    "Create a new qualified opportunity": "Crear una nueva oportunidad cualificada",
    "jue.": "Jue.",
    "<strong>We're sorry but the application doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>": "<strong>Lo sentimos, pero la aplicación no funciona correctamente sin JavaScript habilitado. Por favor, activelo para continuar.</strong>",
    "Closed": "Cerrado",
    "AI Assistant": "Asistente de IA",
    "(1)": "(1)",
    "0. Optin Any Lead": "0. Optin Any Lead",
    "Conversion Rate": "Tasa de conversión",
    "Lost": "Perdido",
    "sáb.": "sáb.",
    "ONB - ONBOARDING": "ONB - INCORPORACIÓN",
    "ONB - ONBOARDING (1)": "ONB - INCORPORACIÓN (1)",
    "Funnel": "Embudo",
    "All": "Todo",
    "-  $ 0.00": "- $ 0.00",
    "0.00%": "0,00%",
    "AndorrA": "AndorrA",
    "(0)": "(0)",
    "-  $ 0.00 (0.00%)": "- $ 0.00 (0.00%)",
    "Stages Distribution": "Distribución de etapas",
    "-  $ 0.00 (100.00%)": "- $ 0.00 (100.00%)",
    "Due Date (ASC)": "Fecha de vencimiento (ASC)",
    "Date Added (ASC)": "Fecha de adición (ASC)",
    "Manual Actions": "Acciones manuales",
    "Due Date (DESC)": "Fecha de vencimiento (DESC)",
    "5. Account Activated": "5. Cuenta activada",
    "6. Free Trial Ended": "6. Prueba gratuita finalizada",
    "4. Account Created": "4. Cuenta creada",
    "Algeria": "Argelia",
    "Won": "Ganado",
    "Google Analytics": "Google Analytics",
    "Date Added (DESC)": "Fecha de adición (DESC)",
    "Onb - Application Survey": "Onb - Encuesta de aplicación",
    "Total Values": "Valores totales",
    "Total Leads": "Clientes potenciales totales",
    "Win %": "% Ganados",
    "0%": "0%",
    "Albania": "Albania",
    "Aland Islands": "Islas Aland",
    "3. Proposal Signed > Onb Form": "3. Propuesta Firmada > Formulario Onb",
    "Canada": "Canada",
    "7. Client > Won": "7. Cliente > Ganado",
    "Workflow - ONB - 1. Application Request": "Flujo de trabajo - ONB - 1. Solicitud de solicitud",
    "Workflow - ONB - 2. Accepted > Sign Proposal": "Flujo de trabajo - ONB - 2. Aceptado > Firmar propuesta",
    "Select Campaign / Workflow": "Seleccione Campaña/Flujo de trabajo",
    "Lost/abandoned": "perdido/abandonado",
    "Highcharts.com": "Highcharts.com",
    "Afghanistan": "Afganistán",
    "American Samoa": "Samoa Americana",
    "Phone": "Teléfono",
    "Cote D\"Ivoire": "Costa de Marfil",
    "Pending": "Pendiente",
    "Antarctica": "Antártida",
    "Workflow - ONB - 4. Onboarding Form Filled > Create Location and Schedule Demo": "Flujo de trabajo - ONB - 4. Formulario de incorporación rellenado > Crear ubicación y programar demostración",
    "Austria": "Austria",
    "Workflow - ONB - 3. Proposal Signed > Send Onboarding Form": "Flujo de trabajo - ONB - 3. Propuesta firmada > Enviar formulario de incorporación",
    "Bahamas": "Bahamas",
    "Azerbaijan": "Azerbaiyán",
    "Bahrain": "Baréin",
    "Cayman Islands": "Islas Caimán",
    "Created with Highcharts 6.2.0": "Creado con Highcharts 6.2.0",
    "1. Application Submitted > Qualify [YES/NO]": "1. Solicitud enviada > Calificar [SÍ/NO]",
    "Belize": "Belice",
    "Bhutan": "Bután",
    "Benin": "Benín",
    "Bolivia": "Bolivia",
    "Belgium": "Bélgica",
    "Botswana": "Botsuana",
    "Belarus": "Bielorrusia",
    "Brazil": "Brasil",
    "Cameroon": "Camerún",
    "British Indian Ocean Territory": "Territorio Británico del Océano Índico",
    "Bulgaria": "Bulgaria",
    "Cambodia": "Camboya",
    "Select Assignee": "Seleccionar cesionario",
    "Croatia": "Croacia",
    "SMS": "SMS",
    "Completed": "Terminado",
    "Bosnia and Herzegovina": "Bosnia y Herzegovina",
    "Bermuda": "islas Bermudas",
    "Go to Manual Actions": "Ir a Acciones manuales",
    "Total Pending": "Pendientes Totales",
    "China": "Porcelana",
    "Cocos (Keeling) Islands": "Islas Cocos (Keeling)",
    "Chad": "Chad",
    "Central African Republic": "República Centroafricana",
    "Congo": "Congo",
    "Colombia": "Colombia",
    "Chile": "Chile",
    "Cook Islands": "Islas Cook",
    "Comoros": "Comoras",
    "Christmas Island": "Isla de Navidad",
    "Barbados": "barbados",
    "Bangladesh": "bangladesh",
    "Make sure your billing address is up to date. This allows us to send updated content, swag and other goodies to you in the future.": "Asegúrate de que tu dirección de facturación esté actualizada. Esto nos permite enviarte contenido actualizado, botín y otras cosas en el futuro.",
    "Congo, The Democratic Republic of the": "Congo, República Democrática del",
    "Australia": "Australia",
    "Aruba": "Aruba",
    "Armenia": "Armenia",
    "Argentina": "Argentina",
    "Burundi": "Burundi",
    "Antigua and Barbuda": "Antigua y Barbuda",
    "Angola": "angola",
    "Anguilla": "anguila",
    "Lead Source Report": "Informe de origen de prospectos",
    "Denmark": "Dinamarca",
    "Czech Republic": "República Checa",
    "Cyprus": "Chipre",
    "Direct": "Directo",
    "How did the call go?": "¿Cómo fue la llamada?",
    "No data to display": "no hay información para mostrar",
    "Cuba": "Cuba",
    "Social": "Social",
    "Egypt": "Egipto",
    "Bouvet Island": "Isla Bouvet",
    "Dominican Republic": "República Dominicana",
    "Dominica": "Dominica",
    "Ecuador": "Ecuador",
    "Organic": "Orgánico",
    "Ethiopia": "Etiopía",
    "Paid": "Pagado",
    "Fiji": "Fiyi",
    "Faroe Islands": "Islas Faroe",
    "Burkina Faso": "Burkina Faso",
    "Busy": "Ocupado",
    "Brunei Darussalam": "Brunei Darussalam",
    "French Polynesia": "Polinesia francés",
    "No Answer": "Sin respuesta",
    "France": "Francia",
    "Finland": "Finlandia",
    "French Guiana": "Guayana Francesa",
    "City required": "Ciudad requerida",
    "Address required": "Dirección requerida",
    "Cape Verde": "Cabo Verde",
    "City*": "Ciudad*",
    "Estonia": "Estonia",
    "Equatorial Guinea": "Guinea Ecuatorial",
    "Eritrea": "Eritrea",
    "Total Page Views": "Páginas vistas en total",
    "Last 12 Months": "Últimos 12 meses",
    "Voicemail": "Mensaje de voz",
    "Address line 2": "Línea de dirección 2",
    "Billing Address*": "Dirección de Envio*",
    "India": "India",
    "There are no tasks assigned for the selected user": "No hay tareas asignadas para el usuario seleccionado",
    "El Salvador": "El Salvador",
    "French Southern Territories": "Territorios Franceses del Sur",
    "Jordan": "Jordán",
    "Falkland Islands (Malvinas)": "Islas Malvinas (Malvinas)",
    "Only Agency Admin can see this": "Solo el administrador de la agencia puede ver esto",
    "Gibraltar": "Gibraltar",
    "Djibouti": "Yibuti",
    "Heard Island and Mcdonald Islands": "Islas Heard e Islas Mcdonald",
    "Germany": "Alemania",
    "Ghana": "Ghana",
    "Guyana": "Guayana",
    "Guinea-Bissau": "Guinea-Bisáu",
    "Honduras": "Honduras",
    "Hungary": "Hungría",
    "Mexico": "México",
    "Haiti": "Haití",
    "Guam": "Guam",
    "Greece": "Grecia",
    "Iceland": "Islandia",
    "Greenland": "Groenlandia",
    "State / Prov / Region *": "Estado / Provincia / Región *",
    "State required": "Estado requerido",
    "Choose country...": "Elige país...",
    "Iraq": "Irak",
    "Isle of Man": "Isla del hombre",
    "Ireland": "Irlanda",
    "Guernsey": "Guernesey",
    "Guinea": "Guinea",
    "Guadeloupe": "Guadalupe",
    "Grenada": "Granada",
    "Guatemala": "Guatemala",
    "Mauritius": "Mauricio",
    "Martinique": "Martinica",
    "Marshall Islands": "Islas Marshall",
    "Mauritania": "Mauritania",
    "Malta": "Malta",
    "Montenegro": "montenegro",
    "Morocco": "Marruecos",
    "Mongolia": "Mongolia",
    "Country*": "País*",
    "Monaco": "Mónaco",
    "Moldova, Republic of": "Moldavia, República de",
    "Gambia": "Gambia",
    "Mozambique": "Mozambique",
    "Georgia": "Georgia",
    "Maldives": "Maldivas",
    "Kyrgyzstan": "Kirguistán",
    "Korea, Republic of": "Corea, república de",
    "Japan": "Japón",
    "Kuwait": "Kuwait",
    "Nauru": "Nauru",
    "Kazakhstan": "Kazajstán",
    "Macedonia, The Former Yugoslav Republic of": "Macedonia, la ex República Yugoslava de",
    "Myanmar": "Birmania",
    "Nepal": "Nepal",
    "Namibia": "Namibia",
    "Netherlands": "Países Bajos",
    "Korea, Democratic People\"S Republic": "Corea, República Popular Democrática",
    "Lao People's Democratic Republic": "República Democrática Popular Lao",
    "Palau": "Palau",
    "Micronesia, Federated States of": "Micronesia, Estados Federados de",
    "Montserrat": "Montserrat",
    "Gabon": "Gabón",
    "Costa Rica": "Costa Rica",
    "Netherlands Antilles": "Antillas Holandesas",
    "Hong Kong": "Hong Kong",
    "Indonesia": "Indonesia",
    "Niue": "Niue",
    "Niger": "Níger",
    "Nicaragua": "Nicaragua",
    "Nigeria": "Nigeria",
    "New Zealand": "Nueva Zelanda",
    "Puerto Rico": "Puerto Rico",
    "Holy See (Vatican City State)": "Santa Sede (Estado de la Ciudad del Vaticano)",
    "Saint Lucia": "Saint Lucia",
    "Lebanon": "Líbano",
    "Norfolk Island": "Isla Norfolk",
    "Northern Mariana Islands": "Islas Marianas del Norte",
    "Macao": "Macao",
    "Madagascar": "Madagascar",
    "Latvia": "letonia",
    "Luxembourg": "luxemburgo",
    "Liechtenstein": "Liechtenstein",
    "Lithuania": "Lituania",
    "Liberia": "Liberia",
    "Israel": "Israel",
    "Italy": "Italia",
    "Jamaica": "Jamaica",
    "Kiribati": "Kiribati",
    "Kenya": "Kenia",
    "Turkey": "Pavo",
    "Jersey": "Jersey",
    "Kosovo": "Kosovo",
    "Turks and Caicos Islands": "Islas Turcas y Caicos",
    "Reunion": "Reunión",
    "Qatar": "Katar",
    "Romania": "Rumania",
    "Saint Kitts and Nevis": "San Cristóbal y Nieves",
    "Saint Martin": "San Martín",
    "Russian Federation": "Federación Rusa",
    "Palestinian Territory, Occupied": "Territorio Palestino, Ocupado",
    "Iran, Islamic Republic Of": "Irán (República Islámica de",
    "New Caledonia": "Nueva Caledonia",
    "Mayotte": "Mayotte",
    "Solomon Islands": "Islas Salomón",
    "Spain": "España",
    "Suriname": "Surinam",
    "Swaziland": "Suazilandia",
    "South Africa": "Sudáfrica",
    "Slovakia": "Eslovaquia",
    "Sudan": "Sudán",
    "Malaysia": "Malasia",
    "Mali": "Tuvieron",
    "Saint Vincent and the Grenadines": "San Vicente y las Granadinas",
    "Tunisia": "Túnez",
    "Peru": "Perú",
    "Paraguay": "Paraguay",
    "Panama": "Panamá",
    "Norway": "Noruega",
    "Pakistan": "Pakistán",
    "South Georgia and the South Sandwich Islands": "Georgia del sur y las islas Sandwich del sur",
    "United States": "Estados Unidos",
    "Tanzania, United Republic of": "Tanzanía, República Unida de",
    "Portugal": "Portugal",
    "Philippines": "Filipinas",
    "Poland": "Polonia",
    "Switzerland": "Suiza",
    "Taiwan": "Taiwán",
    "Syrian Arab Republic": "República Árabe Siria",
    "Tajikistan": "Tayikistán",
    "Sweden": "Suecia",
    "Yes": "Sí",
    "No": "No",
    "Ukraine": "Ucrania",
    "Tuvalu": "Tuvalu",
    ",": ",",
    "Lesotho": "Lesoto",
    "UK": "Reino Unido",
    "Uganda": "Uganda",
    "Malawi": "Malaui",
    "Slovenia": "Eslovenia",
    "Sierra Leone": "Sierra Leona",
    "Saudi Arabia": "Arabia Saudita",
    "Somalia": "Somalia",
    "Serbia": "Serbia",
    "Singapore": "Singapur",
    "Sao Tome and Principe": "Santo Tomé y Príncipe",
    "Senegal": "Senegal",
    "Pitcairn": "pitcairn",
    "and": "y",
    "United States Minor Outlying Islands": "Islas ultramarinas menores de los Estados Unidos",
    "United Arab Emirates": "Emiratos Árabes Unidos",
    "Venezuela": "Venezuela",
    "Virgin Islands, British": "Islas Vírgenes Británicas",
    "Uruguay": "Uruguay",
    "Uzbekistan": "Uzbekistán",
    "Virgin Islands, U.S.": "Islas Vírgenes, EE. UU.",
    "Privacy Policy": "política de privacidad",
    "Vanuatu": "Vanuatu",
    "Western Sahara": "Sahara Occidental",
    "Yemen": "Yemen",
    "Zimbabwe": "Zimbabue",
    "Wallis and Futuna": "Wallis y Futuna",
    "Zambia": "Zambia",
    "Sint Maarten": "San Martín",
    "Trinidad and Tobago": "Trinidad y Tobago",
    "Do you currently resell or intend to resell HighLevel? *": "¿Actualmente revende o tiene la intención de revender HighLevel? *",
    "Rwanda": "Ruanda",
    "Oman": "Mío",
    "Togo": "Ir",
    "Thailand": "Tailandia",
    "Saint Helena": "Santa Elena",
    "Papua New Guinea": "Papúa Nueva Guinea",
    "Postal Code*": "Código Postal*",
    "Postal Code required": "Código postal requerido",
    "Saint Pierre and Miquelon": "San Pedro y Miquelón",
    "Please select any one option": "Por favor seleccione cualquier opción",
    "Timor-Leste": "Timor leyó",
    "Svalbard and Jan Mayen": "Svalbard y Jan Mayen",
    "Sri Lanka": "Sri Lanka",
    "Samoa": "samoa",
    "Seychelles": "Seychelles",
    "Tokelau": "Tokelau",
    "Tonga": "Llegó",
    "Turkmenistan": "turkmenistán",
    "Viet Nam": "Vietnam",
    "I accept HighLevel's": "Acepto HighLevel&#39;s",
    "Country required": "País requerido",
    "Libyan Arab Jamahiriya": "Jamahiriya Árabe Libia",
    "Terms of Service": "Términos de servicio",
    "Address": "DIRECCIÓN",
    "Affilate Policy": "Política de afiliados",
    "City": "Ciudad",
    "Email or phone": "Email o teléfono",
    "Search for a sub-account": "Buscar una subcuenta",
    "Search accounts": "Buscar cuentas",
    "Continue to App": "Continuar a la aplicación",
    "Customer name": "Nombre del cliente",
    "San Marino": "San Marino",
    "Address Line": "Dirección",
    "Postal Code": "Código Postal",
    "State": "Estado",
    "null": "nulo",
    "Templates": "Plantillas",
    "Trigger Links": "Enlaces desencadenantes",
    "Links": "Enlaces",
    "Analyze": "Analizar",
    "Unread": "No leído",
    "Recents": "Recientes",
    "Starred": "Sembrado de estrellas",
    "Quick Filters": "Filtros rápidos",
    "Clear Filters": "Borrar filtros",
    "Assigned (Contact Owner)": "Asignado (contactar con el propietario)",
    "My Chat": "mi chat",
    "Assigned To": "Asignado a",
    "Unassigned": "Sin asignar",
    "Last Message Channel": "Canal de último mensaje",
    "Email": "Correo electrónico",
    "GMB": "GMB",
    "Whatsapp": "Whatsapp",
    "Facebook": "Facebook",
    "Calls": "Llamadas",
    "Instagram": "Instagram",
    "Apply": "Aplicar",
    "3 RESULTS": "3 RESULTADOS",
    "Latest": "El último",
    "Oldest": "Más antiguo",
    "​": "​",
    "Confirm Delete": "Confirmar eliminación",
    "0 conversations will be deleted, along with all the messages & related activities.": "Se eliminarán 0 conversaciones, junto con todos los mensajes.",
    "Delete 0 conversations?": "¿Eliminar 0 conversaciones?",
    "\"DMARC Aggregate Report\"": "\"Informe agregado DMARC\"",
    "Mark as Starred": "Marcar como destacado",
    "Mark as Read": "Marcar como leído",
    "Conversation began": "La conversación comenzó",
    "Sat, 30 Apr 2022, 03:40 AM": "sábado, 30 de abril de 2022, 03:40",
    "30th Apr, 2022": "30 de abril de 2022",
    "12th Jun, 2022": "12 de junio de 2022",
    "Merge fields": "Combinar campos",
    "Contact": "Contacto",
    "User": "Usuario",
    "Appointment": "Cita",
    "Calendar": "Calendario",
    "Campaign": "Campaña",
    "Message": "Mensaje",
    "Account": "Cuenta",
    "Right now": "Ahora mismo",
    "Attribution": "Atribución",
    "Invoice": "Factura",
    "Custom Values": "Valores personalizados",
    "Trigger links": "Activar enlaces",
    "There are issues in your custom variables, please fix them before sending.": "Hay problemas en sus variables personalizadas, corríjalos antes de enviarlos.",
    "Clear": "Claro",
    "Send now": "Enviar ahora",
    "|": "|",
    "Schedule your sms": "Programa tu sms",
    "Date": "Fecha",
    "<": "<",
    "Apr 2023": "abr 2023",
    ">": ">",
    "Mon": "Lun",
    "Tue": "Mar",
    "Wed": "Mie",
    "Thu": "Jue",
    "Fri": "Vie",
    "Sat": "Sab",
    "Sun": "Dom",
    "Time": "Tiempo",
    "9:00 AM": "9:00 AM",
    "Timezone (System)": "Zona horaria (Sistema)",
    "GMT -06:00 America/Mexico_City (CST)": "GMT -06:00 EE. UU./Ciudad de México (CST)",
    "Send schedule": "Enviar horario",
    "Verdana": "Verdana",
    "11pt": "11pt",
    "Formats": "Formatos",
    "0 words": "0 palabras",
    "Powered by": "Energizado por",
    "Tiny": "Diminuto",
    "Schedule your email": "Programe su correo electrónico",
    "Send": "Enviar",
    "\"R": "\"R",
    "Assign to": "Asignar a",
    "Opps, something went wrong :(": "Ups, algo salió mal :(",
    "Retry": "Reintentar",
    "DND": "No molestar",
    "OFF": "APAGADO",
    "CONFIGURE": "CONFIGURAR",
    "Active Workflows": "Flujos de trabajo activos",
    "Create Opportunity": "Crear oportunidad",
    "Book Appointment": "Reservar una cita",
    "Select Template": "Seleccionar plantilla",
    "You don't have any templates yet.": "Aún no tienes ninguna plantilla.",
    "Click here to add one.": "Haga clic aquí para añadir uno.",
    "Add to Workflow": "Agregar al flujo de trabajo",
    "Workflow": "flujo de trabajo",
    "Loading...": "Cargando...",
    "Workflow is required.": "Se requiere flujo de trabajo.",
    "Event Start Date": "Fecha de inicio del evento",
    "...": "...",
    "01": "01",
    "02": "02",
    "03": "03",
    "04": "04",
    "05": "05",
    "06": "06",
    "07": "07",
    "08": "08",
    "09": "09",
    "00": "00",
    "am": "soy",
    "pm": "pm",
    "Now": "Ahora",
    "Request payment": "Solicitar pago",
    "The details that you add below will be added to an invoice link that you can send to \"DMARC Aggregate Report\". Invoices are created within our system and you can track the status of payments": "Los detalles que agregue a continuación se agregarán a un enlace de factura que puede enviar al \"Informe agregado de DMARC\". Las facturas se crean dentro de nuestro sistema y puede realizar un seguimiento del estado de los pagos.",
    "here": "aquí",
    "Contact must be attributed an email/phone to request payment. Please assign an email/phone and try again": "Se debe atribuir al contacto un correo electrónico/teléfono para solicitar el pago. Asigne un correo electrónico/teléfono y vuelva a intentarlo",
    "New message": "Nuevo mensaje",
    "Customer phone": "teléfono del cliente",
    "Send message": "Enviar mensaje",
    "Messages": "Mensajes",
    "Clear Unreads": "Borrar no leídos",
    "Filter": "Filtrar",
    "Filters": "filtros",
    "Chats": "charlas",
    "All chats": "Todos los chats",
    "My chats": "mis chats",
    "No conversations to show": "No hay conversaciones para mostrar",
    "Item name": "Nombre del árticulo",
    "Price": "Precio",
    "Name is required": "Se requiere el nombre",
    "$": "$",
    "Price is required": "Se requiere precio",
    "Add an item": "Agregar un elemento",
    "Total Amount": "Cantidad total",
    "Invoice Due Date:": "Fecha de vencimiento de la factura:",
    "Invoice due date is required": "La fecha de vencimiento de la factura es obligatoria",
    "Additional options": "Opciones adicionales",
    "Payment mode": "Modo de pago",
    "Test": "Prueba",
    "Use setting": "Configuración de uso",
    "Live": "Vivo",
    "Tomorrow": "Mañana",
    "From Name": "De Nombre",
    "From Email": "Desde el e-mail",
    "Subject": "Asunto",
    "Name": "Nombre",
    "Phone Number": "Número de teléfono",
    "Add Tags": "Agregar etiquetas",
    "Select date": "Seleccione fecha",
    "Workflow - ONB - ALL Pipelines > Stale Opp. (# days) > Notify To Assigned User": "Flujo de trabajo - ONB - TODAS las tuberías > Operación detenida (# días) > Notificar a usuario asignado",
    "Appointments": "Citas",
    "Calendar Settings": "Configuración del calendario",
    "I want to": "Yo quiero",
    "Book an Appointment": "Reservar una cita",
    "Add Blocked Off time": "Agregar tiempo bloqueado",
    "ONB - Demo": "ONB - Demostración",
    "Blocked Slots": "Lugares bloqueados",
    "Weekly": "Semanal",
    "Monthly": "Mensual",
    "Daily": "A diario",
    "Today": "Hoy",
    "Sun, 23rd Apr - Sat, 29th Apr": "dom., 23 de abril - sábado, 29 de abril",
    "All Day": "Todo el dia",
    "0 am": "0 a.m.",
    "1 am": "1 a.m.",
    "2 am": "2 a.m.",
    "3 am": "3 a.m.",
    "4 am": "4 a.m.",
    "5 am": "5 a.m.",
    "6 am": "6 a.m.",
    "7 am": "7 a.m.",
    "8 am": "8 a.m.",
    "9 am": "9 a.m.",
    "10 am": "10 a.m.",
    "11 am": "11 a.m.",
    "12 pm": "12 pm",
    "1 pm": "1 pm",
    "2 pm": "2 pm",
    "3 pm": "3 pm",
    "4 pm": "4 pm",
    "5 pm": "5 pm",
    "6 pm": "6 pm",
    "7 pm": "7 pm",
    "8 pm": "8 pm",
    "9 pm": "9 pm",
    "10 pm": "10 pm",
    "11 pm": "11 pm",
    "07:36 pm": "07:36",
    "today": "hoy",
    "America/Mexico_City": "America/Ciudad_de_Mexico",
    "Smart Lists": "Listas inteligentes",
    "Bulk Actions": "Acciones masivas",
    "Restore": "Restaurar",
    "Company": "Compañía",
    "Manage Smart Lists": "Administrar listas inteligentes",
    "* Add filters and save this as a smart list": "* Agregue filtros y guarde esto como una lista inteligente",
    "Columns": "columnas",
    "Created": "Creado",
    "Last Activity": "Última actividad",
    "Tags": "Etiquetas",
    "Address (full)": "Dirección (completa)",
    "Assigned": "Asignado",
    "Birth Date": "Fecha de nacimiento",
    "Business Name": "Nombre del Negocio",
    "Company Name": "nombre de empresa",
    "Grupo de Soporte": "Grupo de Soporte",
    "Last Appointment": "Última cita",
    "Last Note": "última nota",
    "Offers": "ofertas",
    "ONB - Firma": "ONB - Empresa",
    "ONB - Location ID Created": "ONB - ID de ubicación creada",
    "ONB - Subdomain": "ONB - Subdominio",
    "ONB - ¿Eres dentista?": "ONB - ¿Eres dentista?",
    "Opportunity": "Oportunidad",
    "Products": "Productos",
    "Street address": "Dirección",
    "Type": "Tipo",
    "Updated": "Actualizado",
    "Workflows Active": "Flujos de trabajo activos",
    "Workflows Finished": "Flujos de trabajo terminados",
    "¿Cuántos empleados tiene tu cl..": "¿Cuántos empleados tiene tu cl..",
    "¿De qué tamaño es tu base de d..": "¿De qué tamaño es tu base de d..",
    "¿Llevas más de 3 años siendo d..": "¿Llevas más de 3 años siendo d..",
    "¿Te gusta la tecnología y el l..": "¿Te gusta la tecnología y el l..",
    "¿Tienes planeado abrir sucursa..": "¿Tienes planeado abrir sucursa..",
    "More Filters": "Más filtros",
    "Most Used": "Más usado",
    "First Name": "Nombre de pila",
    "Last Name": "Apellido",
    "Tag": "Etiqueta",
    "Wildcard Name": "Nombre comodín",
    "Contact Information": "Información del contacto",
    "Postal Zip Code": "Código postal postal",
    "Street Name": "Nombre de la calle",
    "TikTok LeadId": "ID de cliente potencial de TikTok",
    "Contact Activity": "Actividad de contacto",
    "Import": "Importar",
    "Last Activity Type": "Último tipo de actividad",
    "Workflow (Active)": "Flujo de trabajo (activo)",
    "Workflow (Finished)": "Flujo de trabajo (Terminado)",
    "Opportunity Information": "Información de oportunidad",
    "Age": "Edad",
    "Pipeline": "Tubería",
    "Pipeline Stage": "Etapa de canalización",
    "Pipeline Status": "Estado de la canalización",
    "Membership": "Afiliación",
    "Offer": "Oferta",
    "Product": "Producto",
    "Attribution (Occurence)": "Atribución (Ocurrencia)",
    "Attribution Ad Group Id": "ID de grupo de anuncios de atribución",
    "Attribution Ad Id": "ID de anuncio de atribución",
    "Attribution Campaign": "Campaña de atribución",
    "Attribution Campaign Id": "ID de campaña de atribución",
    "Attribution Content": "Contenido de atribución",
    "Attribution FB ClickId": "Atribución FB ClickId",
    "Attribution Google ClickId": "Atribución Google ClickId",
    "Attribution Keyword": "Palabra clave de atribución",
    "Attribution Match Type": "Tipo de concordancia de atribución",
    "Attribution Medium": "Medio de atribución",
    "Attribution Session Source": "Origen de la sesión de atribución",
    "Attribution Source": "Fuente de atribución",
    "Attribution Term": "Término de atribución",
    "Custom Fields": "Campos Personalizados",
    "¿Cuántos empleados tiene tu clínica dental?": "¿Cuántos empleados tiene tu clínica dental?",
    "¿De qué tamaño es tu base de datos de pacientes?": "¿De qué tamaño es tu base de datos de pacientes?",
    "¿Llevas más de 3 años siendo dentista?": "¿Llevas más de 3 años siendo dentista?",
    "¿Te gusta la tecnología y el lado empresarial de la salud?": "¿Te gusta la tecnología y el lado empresarial de la salud?",
    "¿Tienes planeado abrir sucursales en un futuro no muy lejano (2-5 años)?": "¿Tienes planeado abrir sucursales en un futuro no muy lejano (2-5 años)?",
    "records found": "registros encontrados",
    "Create opportunity": "Crear oportunidad",
    "Send Review Request": "Enviar solicitud de revisión",
    "Bulk Operations": "Operaciones masivas",
    "UU": "EE. UU.",
    "U77777777 U77777777": "U77777777 U77777777",
    "u7u7u7": "u7u7u7",
    "Feb 04 2023": "04 de febrero de 2023",
    "09:39 AM": "09:39",
    "(CST)": "(CST)",
    "JC": "JC",
    "Jhon Conner": "Jhon Connor",
    "na": "ya",
    "Oct 05 2022": "05 oct 2022",
    "04:36 PM": "16:36",
    "(CDT)": "(CDT)",
    "RG": "RG",
    "Rafael Guarin": "Rafael Guarin",
    "Dentistas por Chile": "Dentistas por Chile",
    "Sep 25 2022": "25 de septiembre de 2022",
    "04:40 PM": "16:40",
    "DJ": "DJ",
    "Dr Chebanu Josh": "Dr. Chebanu Josh",
    "Chebanu Aurel DDS": "Chebanu Aurel DDS",
    "Sep 19 2022": "19 de septiembre de 2022",
    "01:55 AM": "01:55",
    "MA": "MA",
    "Marco Alter": "Marco Alter",
    "My Dental": "mi dental",
    "Jul 02 2022": "02 de julio de 2022",
    "06:36 AM": "06:36",
    "9 months ago": "hace 9 meses",
    "[whatsapp error] - whatsapp phone is disconnected": "[error de whatsapp] - el teléfono de whatsapp está desconectado",
    "S": "S",
    "Sss": "Sss",
    "May 20 2022": "20 de mayo de 2022",
    "06:04 PM": "18:04",
    "GC": "GC",
    "Gabriel Murillo Ceballos": "Gabriel Murillo Ceballos",
    "GABRIEL MURILLO": "GABRIEL MURILLO",
    "Apr 30 2022": "30 de abril de 2022",
    "03:11 PM": "15:11",
    "11 months ago": "hace 11 meses",
    "[whatsapp] - message sent from workflow: onb - 1. application request": "[whatsapp] - mensaje enviado desde el flujo de trabajo: onb - 1. solicitud de solicitud",
    "onb - authorize": "onb - autorizar",
    "\"dmarc Aggregate Report\"": "\"Informe agregado de dmarc\"",
    "03:40 AM": "03:40",
    "IG": "IG",
    "Iris Karina Rodríguez Garcés": "Iris Karina Rodríguez Garcés",
    "NOVIDENTAL": "NOVIDENTAL",
    "Apr 27 2022": "27 abr 2022",
    "10:58 PM": "22:58",
    "SS": "SS",
    "S S": "S S",
    "06:16 PM": "18:16",
    "OR": "OR",
    "Oscar Ravelo": "Oscar Ravelo",
    "My Marketing Dream Team": "Equipo de ensueño de My Marketing",
    "04:05 PM": "16:05",
    "10 months ago": "Hace 10 meses",
    "[whatsapp] - message sent from workflow: onb - 2. accepted > sign proposal": "[whatsapp] - mensaje enviado desde flujo de trabajo: onb - 2. aceptado > firmar propuesta",
    "N": "N",
    "Apr 26 2022": "26 abr 2022",
    "11:38 AM": "11:38",
    "AM": "AM",
    "Adriana Guadalupe Marmolejo": "Adriana Guadalupe Marmolejo",
    "tu corazón": "tu corazón",
    "Apr 25 2022": "25 abr 2022",
    "04:00 PM": "16:00",
    "03:33 AM": "03:33",
    "JM": "JM",
    "Josue Mejia": "Josué Mejía",
    "Apr 24 2022": "24 abr 2022",
    "10:04 PM": "22:04",
    "NO": "NO",
    "Nair Orozco": "Nair Orozco",
    "DENTRIKA TEST": "TEXTO DENTRICA",
    "Apr 23 2022": "23 abr 2022",
    "08:04 PM": "20:04",
    "2 months ago": "Hace 2 meses",
    "Quick search": "Búsqueda rápida",
    "Search and add a filter": "Buscar y agregar un filtro",
    "Pipelines": "Tuberías",
    "All Time": "Todo el tiempo",
    "Owner": "Dueño",
    "Abandoned": "Abandonado",
    "New": "Nuevo",
    "Additional Info": "Información adicional",
    "Task": "Tarea",
    "Calendar Event": "Evento de calendario",
    "Note": "Nota",
    "Hide Tags": "Ocultar etiquetas",
    "Hide Assigned To": "Ocultar asignado a",
    "1 Leads": "1 clientes potenciales",
    "ss": "ss",
    "May 20, 2022": "20 de mayo de 2022",
    "+ Task": "+ Tarea",
    "0 Leads": "0 clientes potenciales",
    "3 Leads": "3 clientes potenciales",
    "Apr 30, 2022": "30 de abril de 2022",
    "onb - application survey": "onb - encuesta de aplicación",
    "[whatsapp] - message sent from workflow: onb - 4. onboarding form filled > create location and schedule demo": "[whatsapp] - mensaje enviado desde el flujo de trabajo: onb - 4. formulario de incorporación completado > crear ubicación y programar demostración",
    "Addy Tu Amorcito": "Addy Tu Amorcito",
    "Apr 25, 2022": "25 de abril de 2022",
    "Apr 23, 2022": "23 de abril de 2022",
    "onb - 3. form sign contract": "onb - 3. formulario firmar contrato",
    "2 Leads": "2 clientes potenciales",
    "Apr 27, 2022": "27 de abril de 2022",
    "Invoices": "Facturas",
    "All Invoices": "Todas las facturas",
    "Recurring Templates": "Plantillas recurrentes",
    "Orders": "Pedidos",
    "Subscriptions": "Suscripciones",
    "Transactions": "Actas",
    "Coupons": "Cupones",
    "Tax Settings": "Configuración de impuestos",
    "Integrations": "integraciones",
    "Feedback": "Comentario",
    "Talk to us!": "¡Háblanos!",
    "Have any ideas, troubles or questions?": "¿Tienes alguna idea, problema o pregunta?",
    "From": "De",
    "Attach File": "Adjuntar archivo",
    "Send Message": "Enviar mensaje",
    "Enter a subject": "Introduce un asunto",
    "Social Planner": "planificador social",
    "Emails": "Correos electrónicos",
    "Campaigns": "Campañas",
    "Affiliate Manager": "gerente afiliado",
    "new": "nuevo",
    "Affiliates": "Afiliados",
    "Payouts": "Pagos",
    "Choose a Google My Business location": "Elija una ubicación de Google My Business",
    "There are no GMB locations associated with this account at this moment. Please try to reconnect once you have setup the GMB location.": "No hay ubicaciones de GMB asociadas con esta cuenta en este momento. Intente volver a conectarse una vez que haya configurado la ubicación de GMB.",
    "Choose Facebook pages and groups you want to connect": "Elija las páginas y grupos de Facebook que desea conectar",
    "Pages": "Paginas",
    "You need to be Admin or Page Editor to add it in Social Planner.": "Debe ser administrador o editor de páginas para agregarlo en Social Planner.",
    "There are no pages associated with this account at this moment. Please try to reconnect once you have setup the facebook.": "No hay páginas asociadas con esta cuenta en este momento. Intente volver a conectarse una vez que haya configurado el facebook.",
    "Groups": "Grupos",
    "You need to be a group Admin for any groups you want to add to Social Planner. You also need to LeadConnector added as an app by navigating your Facebook Group's Settings > Advance Settings > Apps.": "Debe ser un administrador de grupo para cualquier grupo que desee agregar a Social Planner. También debe agregar LeadConnector como una aplicación navegando en Configuración de su grupo de Facebook > Configuración avanzada > Aplicaciones.",
    "There are no groups associated with this account at this moment. Please try to reconnect once you have setup the facebook.": "No hay grupos asociados con esta cuenta en este momento. Intente volver a conectarse una vez que haya configurado el facebook.",
    "Add the Instagram Business Account": "Agregar la cuenta comercial de Instagram",
    "Instagram Business profiles have to be connected to Facebook Pages.": "Los perfiles de Instagram Business deben estar conectados a las páginas de Facebook.",
    "1. Log Into Facebook Page to add Instagram": "1. Inicie sesión en la página de Facebook para agregar Instagram",
    "We'll find the Instagram Business profiles that are connected to your Facebook Pages. Otherwise, please go to Facebook Page > Settings > Instagram to link it.": "Encontraremos los perfiles comerciales de Instagram que están conectados a sus páginas de Facebook. De lo contrario, vaya a la página de Facebook  > Configuración  > Instagram para vincularlo.",
    "2. Select the Instagram Business profiles to add to LeadConnector": "2. Seleccione los perfiles comerciales de Instagram para agregar a LeadConnector",
    "Log in to Facebook": "Iniciar sesión en Facebook",
    "Choose Instagram Business Account you want to connect": "Elija la cuenta comercial de Instagram que desea conectar",
    "There are no Instagram Business Accounts associated with any Facebook pages at this moment. Please try to reconnect once you have associated Facebook page for successful configuration to post.": "No hay cuentas comerciales de Instagram asociadas con ninguna página de Facebook en este momento. Intente volver a conectarse una vez que haya asociado la página de Facebook para configurar correctamente la publicación.",
    "Workflows": "Flujos de trabajo",
    "Undefined": "Indefinido",
    "Funnels": "Embudos",
    "Websites": "sitios web",
    "Blogs": "blogs",
    "WordPress": "WordPress",
    "Memberships": "membresías",
    "Analytics": "Analítica",
    "Forms": "formularios",
    "Builder": "Constructor",
    "Submissions": "Presentaciones",
    "Surveys": "Encuestas",
    "Chat Widget": "Widget de chat",
    "Media": "Medios de comunicación",
    "URL Redirects": "Redireccionamientos de URL",
    "Create Folder": "Crear carpeta",
    "New Funnel": "Embudo nuevo",
    "Share Funnel / Website": "Compartir embudo/sitio web",
    "Share this link to give a copy of your funnel / website": "Comparte este enlace para dar una copia de tu embudo/sitio web",
    "Access": "Acceso",
    "Anyone with the link": "Cualquiera con el link",
    "Anyone within My Marketing": "Cualquiera dentro de Mi Marketing",
    "Remove sharing": "Quitar compartir",
    "Share Link": "Compartir enlace",
    "Copy link": "Copiar link",
    "Done": "Hecho",
    "ONB - ONE CLICK ONBOARDING SNAPSHOT": "ONB - INSTANTÁNEA DE INCORPORACIÓN CON UN CLIC",
    "Version 2": "Versión 2",
    "Steps": "Pasos",
    "Edit": "Editar",
    "Clone": "Clon",
    "Move to folder": "Mover a la carpeta",
    "Share": "Compartir",
    "Showing": "Demostración",
    "to": "a",
    "of": "de",
    "items": "elementos",
    "Previous": "Anterior",
    "Next": "Próximo",
    "Create New Funnel": "Crear nuevo embudo",
    "Use Template to create new Funnel": "Use la plantilla para crear un nuevo embudo",
    "Jump start with an awesome prebuilt Funnel.": "Comience con un increíble embudo preconstruido.",
    "Go to Template Library": "Ir a la biblioteca de plantillas",
    "Funnel Name": "Nombre del embudo",
    "Create Funnel": "Crear embudo",
    "Rename Folder": "Renombrar carpeta",
    "Current Name": "Nombre actual",
    "New Name": "Nuevo nombre",
    "Create New Folder": "Crear nueva carpeta",
    "Folder Name": "Nombre de la carpeta",
    "Clone Funnel": "Embudo de clonación",
    "Locations": "Ubicaciones",
    "Search for locations": "Buscar ubicaciones",
    "000 - Autoresponders Recipe": "000 - Receta de respuestas automáticas",
    "000 - Saas Launch Snapshot": "000 - Instantánea de lanzamiento de SaaS",
    "000-affiliate snapshot": "Instantánea de 000 afiliados",
    "000-Empty4Realstatetest": "000-Empty4Realstatetest",
    "0000-CuentaDeAgenciaDEMO": "0000-CuentaDeAgenciaDEMO",
    "001 - ALL CF Templates": "001 - TODAS las plantillas CF",
    "001.1 CF Lead Funnels": "Embudos de plomo 001.1 CF",
    "002 - 300 Funnels": "002 - 300 Embudos",
    "003 - COACHING SNAPSHOT": "003 - INSTANTÁNEA DE ENTRENAMIENTO",
    "004 - Basic Appointments Recipe": "004 - Receta básica de citas",
    "005 - Dentrika Onboarding": "005 - Incorporación de Dentrika",
    "006 - ElMessengerPro": "006 - ElMessengerPro",
    "007 - Warm Up Emails Recipe": "007 - Receta de correos electrónicos de calentamiento",
    "008 - My Marketing*": "008 - Mi comercialización*",
    "009 - Perfect Webinar Snapshot": "009 - Instantánea perfecta del seminario web",
    "010 - One Click Onboarding Snapshot": "010 - Instantánea de incorporación con un clic",
    "011 - Activation Snapshot": "011 - Instantánea de activación",
    "012 - Wardrop Funnels*": "012 - Embudos de gotas de guerra*",
    "013 - Site Skeleton": "013 - Esqueleto del sitio",
    "014 - Small Business Owners Snapshot* [Outdated]": "014 - Resumen de propietarios de pequeñas empresas* [Obsoleto]",
    "015 - Soap Opera Snapshot": "015 - Instantánea de la telenovela",
    "015.1 - Holidays Recipe": "015.1 - Receta navideña",
    "016 - Small Webinar Snapshot": "016 - Pequeña instantánea del seminario web",
    "017 - Saas Websites & Follow Up": "017 - Sitios SaaS",
    "018 - Timestamps Recipe": "018 - Receta de marcas de tiempo",
    "03 - Empty Test": "03 - Prueba vacía",
    "1. jp": "1. jp",
    "10. Funnels imported from clickfunnel - JP": "10. Embudos importados de clickfunnel - JP",
    "2. Marketing Solution Plus Support Portal 2.0 Onboarding - JP": "2. Incorporación de Marketing Solution Plus Support Portal 2.0 - JP",
    "3. English Real State Snapshot - JP": "3. Instantánea de bienes raíces en inglés - JP",
    "Oops! No elements found. Consider changing the search query.": "¡Ups! No se encontraron elementos. Considere cambiar la consulta de búsqueda.",
    "List is empty.": "La lista esta vacía.",
    "Select upto 3 locations": "Seleccione hasta 3 ubicaciones",
    "Cloning is limited to 3 locations at a time": "La clonación está limitada a 3 ubicaciones a la vez",
    "Delete selected item?": "¿Eliminar elemento seleccionado?",
    "This action cannot be reversed.": "Esta acción no se puede revertir.",
    "The selected item will be permanently deleted from your account.": "El elemento seleccionado se eliminará permanentemente de su cuenta.",
    "Confirm deletion by typing 'DELETE' below:": "Confirme la eliminación escribiendo &#39;ELIMINAR&#39; a continuación:",
    "Cancel, Keep": "Cancelar, Mantener",
    "Yes, Delete": "Sí, Eliminar",
    "Move to Folder": "Mover a la carpeta",
    "Folder": "Carpeta",
    "Move to Selected Folder": "Mover a la carpeta seleccionada",
    "Search Funnels": "Embudos de búsqueda",
    "Name for your awesome Funnel": "Nombre para su increíble embudo",
    "": "",
    "Enter new name for folder": "Introduzca un nuevo nombre para la carpeta",
    "Name for your folder": "Nombre para tu carpeta"
}
var txtDicInv = {
    "En": "En",
    "indefinido": "undefined",
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "10",
    "11": "11",
    "12": "12",
    "13": "13",
    "14": "14",
    "15": "15",
    "16": "16",
    "17": "17",
    "18": "18",
    "19": "19",
    "20": "20",
    "21": "21",
    "22": "22",
    "23": "23",
    "24": "24",
    "25": "25",
    "26": "26",
    "27": "27",
    "28": "28",
    "29": "29",
    "30": "30",
    "35": "35",
    "40": "40",
    "45": "45",
    "50": "50",
    "55": "55",
    "2023": "2023",
    "": "",
    "Ajustes": "Settings",
    "×": "×",
    "Enviar una invitación para opinar": "Send a Review Invite",
    "Registro de clientes": "Client Check In",
    "Reserve una nueva cita en el calendario": "Book a new appointment in calendar",
    "MM": "MM",
    "23 de oct. de 2022 - 24 de abr. de 2023": "23 de oct. de 2022 - 24 de abr. de 2023",
    "Nombre del cliente": "Customer name",
    "X": "x",
    "Marketing": "Marketing",
    "Inglés": "English",
    "Ayuda": "Support",
    "Agregar": "Add",
    "Cerrar": "Close",
    "Buscar": "Search",
    "Ignorar": "Ignore",
    "?": "?",
    "Cancelar": "Cancel",
    "mar.": "mar.",
    "Notificaciones": "Notifications",
    "Haga clic aquí": "Click here",
    "Esta semana": "This week",
    "Ahorrar": "Save",
    "Los últimos 7 días": "Last 7 days",
    "Este año": "This year",
    "El año pasado": "Last year",
    "Crear una cita": "Create an Appointment",
    "desconocido": "unknown",
    "Este mes": "This month",
    "Desconectar": "Signout",
    "Automatización": "Automation",
    "Iniciar sesión como": "Login As",
    "calendarios": "Calendars",
    "Contactos": "Contacts",
    "Francés": "French",
    "Ver registro de cambios": "View Changelog",
    "360 Adspy": "360 Adspy",
    "Enviar una solicitud de revisión al personalizador": "Send a review request to the customizer",
    "Portugués (Portugal, Brasil)": "Portuguese (Portugal, Brazil)",
    "Borrar": "Delete",
    "Crear una oportunidad": "Create an Opportunity",
    "para reintegrarse.": "to re-integrate.",
    "Centro de ayuda": "Help Center",
    "Tareas": "Tasks",
    "Enviar una solicitud de revisión": "Send a Review Request",
    "Generador de anuncios": "Ads Generator",
    "Resolver": "Resolve",
    "Seleccione fecha": "Select date",
    "Sitios": "Sites",
    "Italiano": "Italian",
    "La semana pasada": "Last week",
    "Polaco": "Polish",
    "vie.": "vie.",
    "Programar una cita": "Schedule appointment",
    "Añadir oportunidad --": "Add opportunity --",
    "últimos 30 días": "Last 30 days",
    "00:00:00": "00:00:00",
    "Español": "Spanish",
    "ctrl k": "ctrl K",
    "dom.": "dom.",
    "Correo electrónico o teléfono del cliente": "Customer email or phone",
    "Alemán": "German",
    "Panel": "Dashboard",
    "Informes": "Reporting",
    "Pagos": "Payments",
    "Conversaciones": "Conversations",
    "Añade un contacto": "Add a Contact",
    "Oportunidades": "Opportunities",
    "Cambiar a vista de agencia": "Switch to Agency View",
    "lun.": "lun.",
    "Modo privado": "Privacy Mode",
    "Traducir": "Translate",
    "¡Traducir!": "Translate!",
    "El mes pasado": "Last month",
    "Reputación": "Reputation",
    "Mickey Mouse": "Mickey Mouse",
    "Hay un problema con la integración de MailGun de 005 - Dentrika Onboarding.": "There is a problem with the MailGun integration of 005 - Dentrika Onboarding.",
    "mié": "mié.",
    "Agregar un nuevo contacto desde cero": "Add a new Contact from scratch",
    "lombardoalessandro25@hotmail.com": "lombardoalessandro25@hotmail.com",
    "005 - Dentrika Onboarding -- México, CDMX": "005 - Dentrika Onboarding -- Mexico, CDMX",
    "Faltan configuraciones de teléfono para esta cuenta. Póngase en contacto con la agencia": "Phone configurations are missing for this account. Please contact agency",
    "Abril": "abril",
    "$0.00": "$0.00",
    "Abierto": "Open",
    "Acciones rápidas": "Quick Actions",
    "Lanzamiento": "Launchpad",
    "2. SI > Propuesta Enviada": "2. YES > Proposal Sent",
    "Fuente": "Source",
    "Valor de canalización": "Pipeline Value",
    "Crear una nueva oportunidad cualificada": "Create a new qualified opportunity",
    "Jue.": "jue.",
    "<strong>Lo sentimos, pero la aplicación no funciona correctamente sin JavaScript habilitado. Por favor, activelo para continuar.</strong>": "<strong>We're sorry but the application doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>",
    "Cerrado": "Closed",
    "Asistente de IA": "AI Assistant",
    "(1)": "(1)",
    "0. Optin Any Lead": "0. Optin Any Lead",
    "Tasa de conversión": "Conversion Rate",
    "Perdido": "Lost",
    "sáb.": "sáb.",
    "ONB - INCORPORACIÓN": "ONB - ONBOARDING",
    "ONB - INCORPORACIÓN (1)": "ONB - ONBOARDING (1)",
    "Embudo": "Funnel",
    "Todo": "All",
    "- $ 0.00": "-  $ 0.00",
    "0,00%": "0.00%",
    "AndorrA": "AndorrA",
    "(0)": "(0)",
    "- $ 0.00 (0.00%)": "-  $ 0.00 (0.00%)",
    "Distribución de etapas": "Stages Distribution",
    "- $ 0.00 (100.00%)": "-  $ 0.00 (100.00%)",
    "Fecha de vencimiento (ASC)": "Due Date (ASC)",
    "Fecha de adición (ASC)": "Date Added (ASC)",
    "Acciones manuales": "Manual Actions",
    "Fecha de vencimiento (DESC)": "Due Date (DESC)",
    "5. Cuenta activada": "5. Account Activated",
    "6. Prueba gratuita finalizada": "6. Free Trial Ended",
    "4. Cuenta creada": "4. Account Created",
    "Argelia": "Algeria",
    "Ganado": "Won",
    "Google Analytics": "Google Analytics",
    "Fecha de adición (DESC)": "Date Added (DESC)",
    "Onb - Encuesta de aplicación": "Onb - Application Survey",
    "Valores totales": "Total Values",
    "Clientes potenciales totales": "Total Leads",
    "% Ganados": "Win %",
    "0%": "0%",
    "Albania": "Albania",
    "Islas Aland": "Aland Islands",
    "3. Propuesta Firmada > Formulario Onb": "3. Proposal Signed > Onb Form",
    "Canada": "Canada",
    "7. Cliente > Ganado": "7. Client > Won",
    "Flujo de trabajo - ONB - 1. Solicitud de solicitud": "Workflow - ONB - 1. Application Request",
    "Flujo de trabajo - ONB - 2. Aceptado > Firmar propuesta": "Workflow - ONB - 2. Accepted > Sign Proposal",
    "Seleccione Campaña/Flujo de trabajo": "Select Campaign / Workflow",
    "perdido/abandonado": "Lost/abandoned",
    "Highcharts.com": "Highcharts.com",
    "Afganistán": "Afghanistan",
    "Samoa Americana": "American Samoa",
    "Teléfono": "Phone",
    "Costa de Marfil": "Cote D\"Ivoire",
    "Pendiente": "Pending",
    "Antártida": "Antarctica",
    "Flujo de trabajo - ONB - 4. Formulario de incorporación rellenado > Crear ubicación y programar demostración": "Workflow - ONB - 4. Onboarding Form Filled > Create Location and Schedule Demo",
    "Austria": "Austria",
    "Flujo de trabajo - ONB - 3. Propuesta firmada > Enviar formulario de incorporación": "Workflow - ONB - 3. Proposal Signed > Send Onboarding Form",
    "Bahamas": "Bahamas",
    "Azerbaiyán": "Azerbaijan",
    "Baréin": "Bahrain",
    "Islas Caimán": "Cayman Islands",
    "Creado con Highcharts 6.2.0": "Created with Highcharts 6.2.0",
    "1. Solicitud enviada > Calificar [SÍ/NO]": "1. Application Submitted > Qualify [YES/NO]",
    "Belice": "Belize",
    "Bután": "Bhutan",
    "Benín": "Benin",
    "Bolivia": "Bolivia",
    "Bélgica": "Belgium",
    "Botsuana": "Botswana",
    "Bielorrusia": "Belarus",
    "Brasil": "Brazil",
    "Camerún": "Cameroon",
    "Territorio Británico del Océano Índico": "British Indian Ocean Territory",
    "Bulgaria": "Bulgaria",
    "Camboya": "Cambodia",
    "Seleccionar cesionario": "Select Assignee",
    "Croacia": "Croatia",
    "SMS": "SMS",
    "Terminado": "Completed",
    "Bosnia y Herzegovina": "Bosnia and Herzegovina",
    "islas Bermudas": "Bermuda",
    "Ir a Acciones manuales": "Go to Manual Actions",
    "Pendientes Totales": "Total Pending",
    "Porcelana": "China",
    "Islas Cocos (Keeling)": "Cocos (Keeling) Islands",
    "Chad": "Chad",
    "República Centroafricana": "Central African Republic",
    "Congo": "Congo",
    "Colombia": "Colombia",
    "Chile": "Chile",
    "Islas Cook": "Cook Islands",
    "Comoras": "Comoros",
    "Isla de Navidad": "Christmas Island",
    "barbados": "Barbados",
    "bangladesh": "Bangladesh",
    "Asegúrate de que tu dirección de facturación esté actualizada. Esto nos permite enviarte contenido actualizado, botín y otras cosas en el futuro.": "Make sure your billing address is up to date. This allows us to send updated content, swag and other goodies to you in the future.",
    "Congo, República Democrática del": "Congo, The Democratic Republic of the",
    "Australia": "Australia",
    "Aruba": "Aruba",
    "Armenia": "Armenia",
    "Argentina": "Argentina",
    "Burundi": "Burundi",
    "Antigua y Barbuda": "Antigua and Barbuda",
    "angola": "Angola",
    "anguila": "Anguilla",
    "Informe de origen de prospectos": "Lead Source Report",
    "Dinamarca": "Denmark",
    "República Checa": "Czech Republic",
    "Chipre": "Cyprus",
    "Directo": "Direct",
    "¿Cómo fue la llamada?": "How did the call go?",
    "no hay información para mostrar": "No data to display",
    "Cuba": "Cuba",
    "Social": "Social",
    "Egipto": "Egypt",
    "Isla Bouvet": "Bouvet Island",
    "República Dominicana": "Dominican Republic",
    "Dominica": "Dominica",
    "Ecuador": "Ecuador",
    "Orgánico": "Organic",
    "Etiopía": "Ethiopia",
    "Pagado": "Paid",
    "Fiyi": "Fiji",
    "Islas Faroe": "Faroe Islands",
    "Burkina Faso": "Burkina Faso",
    "Ocupado": "Busy",
    "Brunei Darussalam": "Brunei Darussalam",
    "Polinesia francés": "French Polynesia",
    "Sin respuesta": "No Answer",
    "Francia": "France",
    "Finlandia": "Finland",
    "Guayana Francesa": "French Guiana",
    "Ciudad requerida": "City required",
    "Dirección requerida": "Address required",
    "Cabo Verde": "Cape Verde",
    "Ciudad*": "City*",
    "Estonia": "Estonia",
    "Guinea Ecuatorial": "Equatorial Guinea",
    "Eritrea": "Eritrea",
    "Páginas vistas en total": "Total Page Views",
    "Últimos 12 meses": "Last 12 Months",
    "Mensaje de voz": "Voicemail",
    "Línea de dirección 2": "Address line 2",
    "Dirección de Envio*": "Billing Address*",
    "India": "India",
    "No hay tareas asignadas para el usuario seleccionado": "There are no tasks assigned for the selected user",
    "El Salvador": "El Salvador",
    "Territorios Franceses del Sur": "French Southern Territories",
    "Jordán": "Jordan",
    "Islas Malvinas (Malvinas)": "Falkland Islands (Malvinas)",
    "Solo el administrador de la agencia puede ver esto": "Only Agency Admin can see this",
    "Gibraltar": "Gibraltar",
    "Yibuti": "Djibouti",
    "Islas Heard e Islas Mcdonald": "Heard Island and Mcdonald Islands",
    "Alemania": "Germany",
    "Ghana": "Ghana",
    "Guayana": "Guyana",
    "Guinea-Bisáu": "Guinea-Bissau",
    "Honduras": "Honduras",
    "Hungría": "Hungary",
    "México": "Mexico",
    "Haití": "Haiti",
    "Guam": "Guam",
    "Grecia": "Greece",
    "Islandia": "Iceland",
    "Groenlandia": "Greenland",
    "Estado / Provincia / Región *": "State / Prov / Region *",
    "Estado requerido": "State required",
    "Elige país...": "Choose country...",
    "Irak": "Iraq",
    "Isla del hombre": "Isle of Man",
    "Irlanda": "Ireland",
    "Guernesey": "Guernsey",
    "Guinea": "Guinea",
    "Guadalupe": "Guadeloupe",
    "Granada": "Grenada",
    "Guatemala": "Guatemala",
    "Mauricio": "Mauritius",
    "Martinica": "Martinique",
    "Islas Marshall": "Marshall Islands",
    "Mauritania": "Mauritania",
    "Malta": "Malta",
    "montenegro": "Montenegro",
    "Marruecos": "Morocco",
    "Mongolia": "Mongolia",
    "País*": "Country*",
    "Mónaco": "Monaco",
    "Moldavia, República de": "Moldova, Republic of",
    "Gambia": "Gambia",
    "Mozambique": "Mozambique",
    "Georgia": "Georgia",
    "Maldivas": "Maldives",
    "Kirguistán": "Kyrgyzstan",
    "Corea, república de": "Korea, Republic of",
    "Japón": "Japan",
    "Kuwait": "Kuwait",
    "Nauru": "Nauru",
    "Kazajstán": "Kazakhstan",
    "Macedonia, la ex República Yugoslava de": "Macedonia, The Former Yugoslav Republic of",
    "Birmania": "Myanmar",
    "Nepal": "Nepal",
    "Namibia": "Namibia",
    "Países Bajos": "Netherlands",
    "Corea, República Popular Democrática": "Korea, Democratic People\"S Republic",
    "República Democrática Popular Lao": "Lao People's Democratic Republic",
    "Palau": "Palau",
    "Micronesia, Estados Federados de": "Micronesia, Federated States of",
    "Montserrat": "Montserrat",
    "Gabón": "Gabon",
    "Costa Rica": "Costa Rica",
    "Antillas Holandesas": "Netherlands Antilles",
    "Hong Kong": "Hong Kong",
    "Indonesia": "Indonesia",
    "Niue": "Niue",
    "Níger": "Niger",
    "Nicaragua": "Nicaragua",
    "Nigeria": "Nigeria",
    "Nueva Zelanda": "New Zealand",
    "Puerto Rico": "Puerto Rico",
    "Santa Sede (Estado de la Ciudad del Vaticano)": "Holy See (Vatican City State)",
    "Saint Lucia": "Saint Lucia",
    "Líbano": "Lebanon",
    "Isla Norfolk": "Norfolk Island",
    "Islas Marianas del Norte": "Northern Mariana Islands",
    "Macao": "Macao",
    "Madagascar": "Madagascar",
    "letonia": "Latvia",
    "luxemburgo": "Luxembourg",
    "Liechtenstein": "Liechtenstein",
    "Lituania": "Lithuania",
    "Liberia": "Liberia",
    "Israel": "Israel",
    "Italia": "Italy",
    "Jamaica": "Jamaica",
    "Kiribati": "Kiribati",
    "Kenia": "Kenya",
    "Pavo": "Turkey",
    "Jersey": "Jersey",
    "Kosovo": "Kosovo",
    "Islas Turcas y Caicos": "Turks and Caicos Islands",
    "Reunión": "Reunion",
    "Katar": "Qatar",
    "Rumania": "Romania",
    "San Cristóbal y Nieves": "Saint Kitts and Nevis",
    "San Martín": "Sint Maarten",
    "Federación Rusa": "Russian Federation",
    "Territorio Palestino, Ocupado": "Palestinian Territory, Occupied",
    "Irán (República Islámica de": "Iran, Islamic Republic Of",
    "Nueva Caledonia": "New Caledonia",
    "Mayotte": "Mayotte",
    "Islas Salomón": "Solomon Islands",
    "España": "Spain",
    "Surinam": "Suriname",
    "Suazilandia": "Swaziland",
    "Sudáfrica": "South Africa",
    "Eslovaquia": "Slovakia",
    "Sudán": "Sudan",
    "Malasia": "Malaysia",
    "Tuvieron": "Mali",
    "San Vicente y las Granadinas": "Saint Vincent and the Grenadines",
    "Túnez": "Tunisia",
    "Perú": "Peru",
    "Paraguay": "Paraguay",
    "Panamá": "Panama",
    "Noruega": "Norway",
    "Pakistán": "Pakistan",
    "Georgia del sur y las islas Sandwich del sur": "South Georgia and the South Sandwich Islands",
    "Estados Unidos": "United States",
    "Tanzanía, República Unida de": "Tanzania, United Republic of",
    "Portugal": "Portugal",
    "Filipinas": "Philippines",
    "Polonia": "Poland",
    "Suiza": "Switzerland",
    "Taiwán": "Taiwan",
    "República Árabe Siria": "Syrian Arab Republic",
    "Tayikistán": "Tajikistan",
    "Suecia": "Sweden",
    "Sí": "Yes",
    "No": "No",
    "Ucrania": "Ukraine",
    "Tuvalu": "Tuvalu",
    ",": ",",
    "Lesoto": "Lesotho",
    "Reino Unido": "UK",
    "Uganda": "Uganda",
    "Malaui": "Malawi",
    "Eslovenia": "Slovenia",
    "Sierra Leona": "Sierra Leone",
    "Arabia Saudita": "Saudi Arabia",
    "Somalia": "Somalia",
    "Serbia": "Serbia",
    "Singapur": "Singapore",
    "Santo Tomé y Príncipe": "Sao Tome and Principe",
    "Senegal": "Senegal",
    "pitcairn": "Pitcairn",
    "y": "and",
    "Islas ultramarinas menores de los Estados Unidos": "United States Minor Outlying Islands",
    "Emiratos Árabes Unidos": "United Arab Emirates",
    "Venezuela": "Venezuela",
    "Islas Vírgenes Británicas": "Virgin Islands, British",
    "Uruguay": "Uruguay",
    "Uzbekistán": "Uzbekistan",
    "Islas Vírgenes, EE. UU.": "Virgin Islands, U.S.",
    "política de privacidad": "Privacy Policy",
    "Vanuatu": "Vanuatu",
    "Sahara Occidental": "Western Sahara",
    "Yemen": "Yemen",
    "Zimbabue": "Zimbabwe",
    "Wallis y Futuna": "Wallis and Futuna",
    "Zambia": "Zambia",
    "Trinidad y Tobago": "Trinidad and Tobago",
    "¿Actualmente revende o tiene la intención de revender HighLevel? *": "Do you currently resell or intend to resell HighLevel? *",
    "Ruanda": "Rwanda",
    "Mío": "Oman",
    "Ir": "Togo",
    "Tailandia": "Thailand",
    "Santa Elena": "Saint Helena",
    "Papúa Nueva Guinea": "Papua New Guinea",
    "Código Postal*": "Postal Code*",
    "Código postal requerido": "Postal Code required",
    "San Pedro y Miquelón": "Saint Pierre and Miquelon",
    "Por favor seleccione cualquier opción": "Please select any one option",
    "Timor leyó": "Timor-Leste",
    "Svalbard y Jan Mayen": "Svalbard and Jan Mayen",
    "Sri Lanka": "Sri Lanka",
    "samoa": "Samoa",
    "Seychelles": "Seychelles",
    "Tokelau": "Tokelau",
    "Llegó": "Tonga",
    "turkmenistán": "Turkmenistan",
    "Vietnam": "Viet Nam",
    "Acepto HighLevel&#39;s": "I accept HighLevel's",
    "País requerido": "Country required",
    "Jamahiriya Árabe Libia": "Libyan Arab Jamahiriya",
    "Términos de servicio": "Terms of Service",
    "DIRECCIÓN": "Address",
    "Política de afiliados": "Affilate Policy",
    "Ciudad": "City",
    "Email o teléfono": "Email or phone",
    "Buscar una subcuenta": "Search for a sub-account",
    "Buscar cuentas": "Search accounts",
    "Continuar a la aplicación": "Continue to App",
    "San Marino": "San Marino",
    "Dirección": "Street address",
    "Código Postal": "Postal Code",
    "Estado": "State",
    "nulo": "null",
    "Plantillas": "Templates",
    "Enlaces desencadenantes": "Trigger Links",
    "Enlaces": "Links",
    "Analizar": "Analyze",
    "No leído": "Unread",
    "Recientes": "Recents",
    "Sembrado de estrellas": "Starred",
    "Filtros rápidos": "Quick Filters",
    "Borrar filtros": "Clear Filters",
    "Asignado (contactar con el propietario)": "Assigned (Contact Owner)",
    "mi chat": "My Chat",
    "Asignado a": "Assigned To",
    "Sin asignar": "Unassigned",
    "Canal de último mensaje": "Last Message Channel",
    "Correo electrónico": "Email",
    "GMB": "GMB",
    "Whatsapp": "Whatsapp",
    "Facebook": "Facebook",
    "Llamadas": "Calls",
    "Instagram": "Instagram",
    "Aplicar": "Apply",
    "3 RESULTADOS": "3 RESULTS",
    "El último": "Latest",
    "Más antiguo": "Oldest",
    "​": "​",
    "Confirmar eliminación": "Confirm Delete",
    "Se eliminarán 0 conversaciones, junto con todos los mensajes.": "0 conversations will be deleted, along with all the messages & related activities.",
    "¿Eliminar 0 conversaciones?": "Delete 0 conversations?",
    "\"Informe agregado DMARC\"": "\"DMARC Aggregate Report\"",
    "Marcar como destacado": "Mark as Starred",
    "Marcar como leído": "Mark as Read",
    "La conversación comenzó": "Conversation began",
    "sábado, 30 de abril de 2022, 03:40": "Sat, 30 Apr 2022, 03:40 AM",
    "30 de abril de 2022": "Apr 30, 2022",
    "12 de junio de 2022": "12th Jun, 2022",
    "Combinar campos": "Merge fields",
    "Contacto": "Contact",
    "Usuario": "User",
    "Cita": "Appointment",
    "Calendario": "Calendar",
    "Campaña": "Campaign",
    "Mensaje": "Message",
    "Cuenta": "Account",
    "Ahora mismo": "Right now",
    "Atribución": "Attribution",
    "Factura": "Invoice",
    "Valores personalizados": "Custom Values",
    "Activar enlaces": "Trigger links",
    "Hay problemas en sus variables personalizadas, corríjalos antes de enviarlos.": "There are issues in your custom variables, please fix them before sending.",
    "Claro": "Clear",
    "Enviar ahora": "Send now",
    "|": "|",
    "Programa tu sms": "Schedule your sms",
    "Fecha": "Date",
    "<": "<",
    "abr 2023": "Apr 2023",
    ">": ">",
    "Lun": "Mon",
    "Mar": "Tue",
    "Mie": "Wed",
    "Jue": "Thu",
    "Vie": "Fri",
    "Sab": "Sat",
    "Dom": "Sun",
    "Tiempo": "Time",
    "9:00 AM": "9:00 AM",
    "Zona horaria (Sistema)": "Timezone (System)",
    "GMT -06:00 EE. UU./Ciudad de México (CST)": "GMT -06:00 America/Mexico_City (CST)",
    "Enviar horario": "Send schedule",
    "Verdana": "Verdana",
    "11pt": "11pt",
    "Formatos": "Formats",
    "0 palabras": "0 words",
    "Energizado por": "Powered by",
    "Diminuto": "Tiny",
    "Programe su correo electrónico": "Schedule your email",
    "Enviar": "Send",
    "\"R": "\"R",
    "Asignar a": "Assign to",
    "Ups, algo salió mal :(": "Opps, something went wrong :(",
    "Reintentar": "Retry",
    "No molestar": "DND",
    "APAGADO": "OFF",
    "CONFIGURAR": "CONFIGURE",
    "Flujos de trabajo activos": "Workflows Active",
    "Crear oportunidad": "Create opportunity",
    "Reservar una cita": "Book an Appointment",
    "Seleccionar plantilla": "Select Template",
    "Aún no tienes ninguna plantilla.": "You don't have any templates yet.",
    "Haga clic aquí para añadir uno.": "Click here to add one.",
    "Agregar al flujo de trabajo": "Add to Workflow",
    "flujo de trabajo": "Workflow",
    "Cargando...": "Loading...",
    "Se requiere flujo de trabajo.": "Workflow is required.",
    "Fecha de inicio del evento": "Event Start Date",
    "...": "...",
    "01": "01",
    "02": "02",
    "03": "03",
    "04": "04",
    "05": "05",
    "06": "06",
    "07": "07",
    "08": "08",
    "09": "09",
    "00": "00",
    "soy": "am",
    "pm": "pm",
    "Ahora": "Now",
    "Solicitar pago": "Request payment",
    "Los detalles que agregue a continuación se agregarán a un enlace de factura que puede enviar al \"Informe agregado de DMARC\". Las facturas se crean dentro de nuestro sistema y puede realizar un seguimiento del estado de los pagos.": "The details that you add below will be added to an invoice link that you can send to \"DMARC Aggregate Report\". Invoices are created within our system and you can track the status of payments",
    "aquí": "here",
    "Se debe atribuir al contacto un correo electrónico/teléfono para solicitar el pago. Asigne un correo electrónico/teléfono y vuelva a intentarlo": "Contact must be attributed an email/phone to request payment. Please assign an email/phone and try again",
    "Nuevo mensaje": "New message",
    "teléfono del cliente": "Customer phone",
    "Enviar mensaje": "Send Message",
    "Mensajes": "Messages",
    "Borrar no leídos": "Clear Unreads",
    "Filtrar": "Filter",
    "filtros": "Filters",
    "charlas": "Chats",
    "Todos los chats": "All chats",
    "mis chats": "My chats",
    "No hay conversaciones para mostrar": "No conversations to show",
    "Nombre del árticulo": "Item name",
    "Precio": "Price",
    "Se requiere el nombre": "Name is required",
    "$": "$",
    "Se requiere precio": "Price is required",
    "Agregar un elemento": "Add an item",
    "Cantidad total": "Total Amount",
    "Fecha de vencimiento de la factura:": "Invoice Due Date:",
    "La fecha de vencimiento de la factura es obligatoria": "Invoice due date is required",
    "Opciones adicionales": "Additional options",
    "Modo de pago": "Payment mode",
    "Prueba": "Test",
    "Configuración de uso": "Use setting",
    "Vivo": "Live",
    "Mañana": "Tomorrow",
    "De Nombre": "From Name",
    "Desde el e-mail": "From Email",
    "Asunto": "Subject",
    "Nombre": "Name",
    "Número de teléfono": "Phone Number",
    "Agregar etiquetas": "Add Tags",
    "Flujo de trabajo - ONB - TODAS las tuberías > Operación detenida (# días) > Notificar a usuario asignado": "Workflow - ONB - ALL Pipelines > Stale Opp. (# days) > Notify To Assigned User",
    "Citas": "Appointments",
    "Configuración del calendario": "Calendar Settings",
    "Yo quiero": "I want to",
    "Agregar tiempo bloqueado": "Add Blocked Off time",
    "ONB - Demostración": "ONB - Demo",
    "Lugares bloqueados": "Blocked Slots",
    "Semanal": "Weekly",
    "Mensual": "Monthly",
    "A diario": "Daily",
    "Hoy": "Today",
    "dom., 23 de abril - sábado, 29 de abril": "Sun, 23rd Apr - Sat, 29th Apr",
    "Todo el dia": "All Day",
    "0 a.m.": "0 am",
    "1 a.m.": "1 am",
    "2 a.m.": "2 am",
    "3 a.m.": "3 am",
    "4 a.m.": "4 am",
    "5 a.m.": "5 am",
    "6 a.m.": "6 am",
    "7 a.m.": "7 am",
    "8 a.m.": "8 am",
    "9 a.m.": "9 am",
    "10 a.m.": "10 am",
    "11 a.m.": "11 am",
    "12 pm": "12 pm",
    "1 pm": "1 pm",
    "2 pm": "2 pm",
    "3 pm": "3 pm",
    "4 pm": "4 pm",
    "5 pm": "5 pm",
    "6 pm": "6 pm",
    "7 pm": "7 pm",
    "8 pm": "8 pm",
    "9 pm": "9 pm",
    "10 pm": "10 pm",
    "11 pm": "11 pm",
    "07:36": "07:36 pm",
    "hoy": "today",
    "America/Ciudad_de_Mexico": "America/Mexico_City",
    "Listas inteligentes": "Smart Lists",
    "Acciones masivas": "Bulk Actions",
    "Restaurar": "Restore",
    "Compañía": "Company",
    "Administrar listas inteligentes": "Manage Smart Lists",
    "* Agregue filtros y guarde esto como una lista inteligente": "* Add filters and save this as a smart list",
    "columnas": "Columns",
    "Creado": "Created",
    "Última actividad": "Last Activity",
    "Etiquetas": "Tags",
    "Dirección (completa)": "Address (full)",
    "Asignado": "Assigned",
    "Fecha de nacimiento": "Birth Date",
    "Nombre del Negocio": "Business Name",
    "nombre de empresa": "Company Name",
    "Grupo de Soporte": "Grupo de Soporte",
    "Última cita": "Last Appointment",
    "última nota": "Last Note",
    "ofertas": "Offers",
    "ONB - Empresa": "ONB - Firma",
    "ONB - ID de ubicación creada": "ONB - Location ID Created",
    "ONB - Subdominio": "ONB - Subdomain",
    "ONB - ¿Eres dentista?": "ONB - ¿Eres dentista?",
    "Oportunidad": "Opportunity",
    "Productos": "Products",
    "Tipo": "Type",
    "Actualizado": "Updated",
    "Flujos de trabajo terminados": "Workflows Finished",
    "¿Cuántos empleados tiene tu cl..": "¿Cuántos empleados tiene tu cl..",
    "¿De qué tamaño es tu base de d..": "¿De qué tamaño es tu base de d..",
    "¿Llevas más de 3 años siendo d..": "¿Llevas más de 3 años siendo d..",
    "¿Te gusta la tecnología y el l..": "¿Te gusta la tecnología y el l..",
    "¿Tienes planeado abrir sucursa..": "¿Tienes planeado abrir sucursa..",
    "Más filtros": "More Filters",
    "Más usado": "Most Used",
    "Nombre de pila": "First Name",
    "Apellido": "Last Name",
    "Etiqueta": "Tag",
    "Nombre comodín": "Wildcard Name",
    "Información del contacto": "Contact Information",
    "Código postal postal": "Postal Zip Code",
    "Nombre de la calle": "Street Name",
    "ID de cliente potencial de TikTok": "TikTok LeadId",
    "Actividad de contacto": "Contact Activity",
    "Importar": "Import",
    "Último tipo de actividad": "Last Activity Type",
    "Flujo de trabajo (activo)": "Workflow (Active)",
    "Flujo de trabajo (Terminado)": "Workflow (Finished)",
    "Información de oportunidad": "Opportunity Information",
    "Edad": "Age",
    "Tubería": "Pipeline",
    "Etapa de canalización": "Pipeline Stage",
    "Estado de la canalización": "Pipeline Status",
    "Afiliación": "Membership",
    "Oferta": "Offer",
    "Producto": "Product",
    "Atribución (Ocurrencia)": "Attribution (Occurence)",
    "ID de grupo de anuncios de atribución": "Attribution Ad Group Id",
    "ID de anuncio de atribución": "Attribution Ad Id",
    "Campaña de atribución": "Attribution Campaign",
    "ID de campaña de atribución": "Attribution Campaign Id",
    "Contenido de atribución": "Attribution Content",
    "Atribución FB ClickId": "Attribution FB ClickId",
    "Atribución Google ClickId": "Attribution Google ClickId",
    "Palabra clave de atribución": "Attribution Keyword",
    "Tipo de concordancia de atribución": "Attribution Match Type",
    "Medio de atribución": "Attribution Medium",
    "Origen de la sesión de atribución": "Attribution Session Source",
    "Fuente de atribución": "Attribution Source",
    "Término de atribución": "Attribution Term",
    "Campos Personalizados": "Custom Fields",
    "¿Cuántos empleados tiene tu clínica dental?": "¿Cuántos empleados tiene tu clínica dental?",
    "¿De qué tamaño es tu base de datos de pacientes?": "¿De qué tamaño es tu base de datos de pacientes?",
    "¿Llevas más de 3 años siendo dentista?": "¿Llevas más de 3 años siendo dentista?",
    "¿Te gusta la tecnología y el lado empresarial de la salud?": "¿Te gusta la tecnología y el lado empresarial de la salud?",
    "¿Tienes planeado abrir sucursales en un futuro no muy lejano (2-5 años)?": "¿Tienes planeado abrir sucursales en un futuro no muy lejano (2-5 años)?",
    "registros encontrados": "records found",
    "Enviar solicitud de revisión": "Send Review Request",
    "Operaciones masivas": "Bulk Operations",
    "EE. UU.": "UU",
    "U77777777 U77777777": "U77777777 U77777777",
    "u7u7u7": "u7u7u7",
    "04 de febrero de 2023": "Feb 04 2023",
    "09:39": "09:39 AM",
    "(CST)": "(CST)",
    "JC": "JC",
    "Jhon Connor": "Jhon Conner",
    "ya": "na",
    "05 oct 2022": "Oct 05 2022",
    "16:36": "04:36 PM",
    "(CDT)": "(CDT)",
    "RG": "RG",
    "Rafael Guarin": "Rafael Guarin",
    "Dentistas por Chile": "Dentistas por Chile",
    "25 de septiembre de 2022": "Sep 25 2022",
    "16:40": "04:40 PM",
    "DJ": "DJ",
    "Dr. Chebanu Josh": "Dr Chebanu Josh",
    "Chebanu Aurel DDS": "Chebanu Aurel DDS",
    "19 de septiembre de 2022": "Sep 19 2022",
    "01:55": "01:55 AM",
    "MA": "MA",
    "Marco Alter": "Marco Alter",
    "mi dental": "My Dental",
    "02 de julio de 2022": "Jul 02 2022",
    "06:36": "06:36 AM",
    "hace 9 meses": "9 months ago",
    "[error de whatsapp] - el teléfono de whatsapp está desconectado": "[whatsapp error] - whatsapp phone is disconnected",
    "S": "S",
    "Sss": "Sss",
    "20 de mayo de 2022": "May 20, 2022",
    "18:04": "06:04 PM",
    "GC": "GC",
    "Gabriel Murillo Ceballos": "Gabriel Murillo Ceballos",
    "GABRIEL MURILLO": "GABRIEL MURILLO",
    "15:11": "03:11 PM",
    "hace 11 meses": "11 months ago",
    "[whatsapp] - mensaje enviado desde el flujo de trabajo: onb - 1. solicitud de solicitud": "[whatsapp] - message sent from workflow: onb - 1. application request",
    "onb - autorizar": "onb - authorize",
    "\"Informe agregado de dmarc\"": "\"dmarc Aggregate Report\"",
    "03:40": "03:40 AM",
    "IG": "IG",
    "Iris Karina Rodríguez Garcés": "Iris Karina Rodríguez Garcés",
    "NOVIDENTAL": "NOVIDENTAL",
    "27 abr 2022": "Apr 27 2022",
    "22:58": "10:58 PM",
    "SS": "SS",
    "S S": "S S",
    "18:16": "06:16 PM",
    "OR": "OR",
    "Oscar Ravelo": "Oscar Ravelo",
    "Equipo de ensueño de My Marketing": "My Marketing Dream Team",
    "16:05": "04:05 PM",
    "Hace 10 meses": "10 months ago",
    "[whatsapp] - mensaje enviado desde flujo de trabajo: onb - 2. aceptado > firmar propuesta": "[whatsapp] - message sent from workflow: onb - 2. accepted > sign proposal",
    "N": "N",
    "26 abr 2022": "Apr 26 2022",
    "11:38": "11:38 AM",
    "AM": "AM",
    "Adriana Guadalupe Marmolejo": "Adriana Guadalupe Marmolejo",
    "tu corazón": "tu corazón",
    "25 abr 2022": "Apr 25 2022",
    "16:00": "04:00 PM",
    "03:33": "03:33 AM",
    "JM": "JM",
    "Josué Mejía": "Josue Mejia",
    "24 abr 2022": "Apr 24 2022",
    "22:04": "10:04 PM",
    "NO": "NO",
    "Nair Orozco": "Nair Orozco",
    "TEXTO DENTRICA": "DENTRIKA TEST",
    "23 abr 2022": "Apr 23 2022",
    "20:04": "08:04 PM",
    "Hace 2 meses": "2 months ago",
    "Búsqueda rápida": "Quick search",
    "Buscar y agregar un filtro": "Search and add a filter",
    "Tuberías": "Pipelines",
    "Todo el tiempo": "All Time",
    "Dueño": "Owner",
    "Abandonado": "Abandoned",
    "Nuevo": "New",
    "Información adicional": "Additional Info",
    "Tarea": "Task",
    "Evento de calendario": "Calendar Event",
    "Nota": "Note",
    "Ocultar etiquetas": "Hide Tags",
    "Ocultar asignado a": "Hide Assigned To",
    "1 clientes potenciales": "1 Leads",
    "ss": "ss",
    "+ Tarea": "+ Task",
    "0 clientes potenciales": "0 Leads",
    "3 clientes potenciales": "3 Leads",
    "onb - encuesta de aplicación": "onb - application survey",
    "[whatsapp] - mensaje enviado desde el flujo de trabajo: onb - 4. formulario de incorporación completado > crear ubicación y programar demostración": "[whatsapp] - message sent from workflow: onb - 4. onboarding form filled > create location and schedule demo",
    "Addy Tu Amorcito": "Addy Tu Amorcito",
    "25 de abril de 2022": "Apr 25, 2022",
    "23 de abril de 2022": "Apr 23, 2022",
    "onb - 3. formulario firmar contrato": "onb - 3. form sign contract",
    "2 clientes potenciales": "2 Leads",
    "27 de abril de 2022": "Apr 27, 2022",
    "Facturas": "Invoices",
    "Todas las facturas": "All Invoices",
    "Plantillas recurrentes": "Recurring Templates",
    "Pedidos": "Orders",
    "Suscripciones": "Subscriptions",
    "Actas": "Transactions",
    "Cupones": "Coupons",
    "Configuración de impuestos": "Tax Settings",
    "integraciones": "Integrations",
    "Comentario": "Feedback",
    "¡Háblanos!": "Talk to us!",
    "¿Tienes alguna idea, problema o pregunta?": "Have any ideas, troubles or questions?",
    "De": "From",
    "Adjuntar archivo": "Attach File",
    "Introduce un asunto": "Enter a subject",
    "planificador social": "Social Planner",
    "Correos electrónicos": "Emails",
    "Campañas": "Campaigns",
    "gerente afiliado": "Affiliate Manager",
    "nuevo": "new",
    "Afiliados": "Affiliates",
    "Elija una ubicación de Google My Business": "Choose a Google My Business location",
    "No hay ubicaciones de GMB asociadas con esta cuenta en este momento. Intente volver a conectarse una vez que haya configurado la ubicación de GMB.": "There are no GMB locations associated with this account at this moment. Please try to reconnect once you have setup the GMB location.",
    "Elija las páginas y grupos de Facebook que desea conectar": "Choose Facebook pages and groups you want to connect",
    "Paginas": "Pages",
    "Debe ser administrador o editor de páginas para agregarlo en Social Planner.": "You need to be Admin or Page Editor to add it in Social Planner.",
    "No hay páginas asociadas con esta cuenta en este momento. Intente volver a conectarse una vez que haya configurado el facebook.": "There are no pages associated with this account at this moment. Please try to reconnect once you have setup the facebook.",
    "Grupos": "Groups",
    "Debe ser un administrador de grupo para cualquier grupo que desee agregar a Social Planner. También debe agregar LeadConnector como una aplicación navegando en Configuración de su grupo de Facebook > Configuración avanzada > Aplicaciones.": "You need to be a group Admin for any groups you want to add to Social Planner. You also need to LeadConnector added as an app by navigating your Facebook Group's Settings > Advance Settings > Apps.",
    "No hay grupos asociados con esta cuenta en este momento. Intente volver a conectarse una vez que haya configurado el facebook.": "There are no groups associated with this account at this moment. Please try to reconnect once you have setup the facebook.",
    "Agregar la cuenta comercial de Instagram": "Add the Instagram Business Account",
    "Los perfiles de Instagram Business deben estar conectados a las páginas de Facebook.": "Instagram Business profiles have to be connected to Facebook Pages.",
    "1. Inicie sesión en la página de Facebook para agregar Instagram": "1. Log Into Facebook Page to add Instagram",
    "Encontraremos los perfiles comerciales de Instagram que están conectados a sus páginas de Facebook. De lo contrario, vaya a la página de Facebook  > Configuración  > Instagram para vincularlo.": "We'll find the Instagram Business profiles that are connected to your Facebook Pages. Otherwise, please go to Facebook Page > Settings > Instagram to link it.",
    "2. Seleccione los perfiles comerciales de Instagram para agregar a LeadConnector": "2. Select the Instagram Business profiles to add to LeadConnector",
    "Iniciar sesión en Facebook": "Log in to Facebook",
    "Elija la cuenta comercial de Instagram que desea conectar": "Choose Instagram Business Account you want to connect",
    "No hay cuentas comerciales de Instagram asociadas con ninguna página de Facebook en este momento. Intente volver a conectarse una vez que haya asociado la página de Facebook para configurar correctamente la publicación.": "There are no Instagram Business Accounts associated with any Facebook pages at this moment. Please try to reconnect once you have associated Facebook page for successful configuration to post.",
    "Flujos de trabajo": "Workflows",
    "Indefinido": "Undefined",
    "Embudos": "Funnels",
    "sitios web": "Websites",
    "blogs": "Blogs",
    "WordPress": "WordPress",
    "membresías": "Memberships",
    "Analítica": "Analytics",
    "formularios": "Forms",
    "Constructor": "Builder",
    "Presentaciones": "Submissions",
    "Encuestas": "Surveys",
    "Widget de chat": "Chat Widget",
    "Medios de comunicación": "Media",
    "Redireccionamientos de URL": "URL Redirects",
    "Crear carpeta": "Create Folder",
    "Embudo nuevo": "New Funnel",
    "Compartir embudo/sitio web": "Share Funnel / Website",
    "Comparte este enlace para dar una copia de tu embudo/sitio web": "Share this link to give a copy of your funnel / website",
    "Acceso": "Access",
    "Cualquiera con el link": "Anyone with the link",
    "Cualquiera dentro de Mi Marketing": "Anyone within My Marketing",
    "Quitar compartir": "Remove sharing",
    "Compartir enlace": "Share Link",
    "Copiar link": "Copy link",
    "Hecho": "Done",
    "ONB - INSTANTÁNEA DE INCORPORACIÓN CON UN CLIC": "ONB - ONE CLICK ONBOARDING SNAPSHOT",
    "Versión 2": "Version 2",
    "Pasos": "Steps",
    "Editar": "Edit",
    "Clon": "Clone",
    "Mover a la carpeta": "Move to Folder",
    "Compartir": "Share",
    "Demostración": "Showing",
    "a": "to",
    "de": "of",
    "elementos": "items",
    "Anterior": "Previous",
    "Próximo": "Next",
    "Crear nuevo embudo": "Create New Funnel",
    "Use la plantilla para crear un nuevo embudo": "Use Template to create new Funnel",
    "Comience con un increíble embudo preconstruido.": "Jump start with an awesome prebuilt Funnel.",
    "Ir a la biblioteca de plantillas": "Go to Template Library",
    "Nombre del embudo": "Funnel Name",
    "Crear embudo": "Create Funnel",
    "Renombrar carpeta": "Rename Folder",
    "Nombre actual": "Current Name",
    "Nuevo nombre": "New Name",
    "Crear nueva carpeta": "Create New Folder",
    "Nombre de la carpeta": "Folder Name",
    "Embudo de clonación": "Clone Funnel",
    "Ubicaciones": "Locations",
    "Buscar ubicaciones": "Search for locations",
    "000 - Receta de respuestas automáticas": "000 - Autoresponders Recipe",
    "000 - Instantánea de lanzamiento de SaaS": "000 - Saas Launch Snapshot",
    "Instantánea de 000 afiliados": "000-affiliate snapshot",
    "000-Empty4Realstatetest": "000-Empty4Realstatetest",
    "0000-CuentaDeAgenciaDEMO": "0000-CuentaDeAgenciaDEMO",
    "001 - TODAS las plantillas CF": "001 - ALL CF Templates",
    "Embudos de plomo 001.1 CF": "001.1 CF Lead Funnels",
    "002 - 300 Embudos": "002 - 300 Funnels",
    "003 - INSTANTÁNEA DE ENTRENAMIENTO": "003 - COACHING SNAPSHOT",
    "004 - Receta básica de citas": "004 - Basic Appointments Recipe",
    "005 - Incorporación de Dentrika": "005 - Dentrika Onboarding",
    "006 - ElMessengerPro": "006 - ElMessengerPro",
    "007 - Receta de correos electrónicos de calentamiento": "007 - Warm Up Emails Recipe",
    "008 - Mi comercialización*": "008 - My Marketing*",
    "009 - Instantánea perfecta del seminario web": "009 - Perfect Webinar Snapshot",
    "010 - Instantánea de incorporación con un clic": "010 - One Click Onboarding Snapshot",
    "011 - Instantánea de activación": "011 - Activation Snapshot",
    "012 - Embudos de gotas de guerra*": "012 - Wardrop Funnels*",
    "013 - Esqueleto del sitio": "013 - Site Skeleton",
    "014 - Resumen de propietarios de pequeñas empresas* [Obsoleto]": "014 - Small Business Owners Snapshot* [Outdated]",
    "015 - Instantánea de la telenovela": "015 - Soap Opera Snapshot",
    "015.1 - Receta navideña": "015.1 - Holidays Recipe",
    "016 - Pequeña instantánea del seminario web": "016 - Small Webinar Snapshot",
    "017 - Sitios SaaS": "017 - Saas Websites & Follow Up",
    "018 - Receta de marcas de tiempo": "018 - Timestamps Recipe",
    "03 - Prueba vacía": "03 - Empty Test",
    "1. jp": "1. jp",
    "10. Embudos importados de clickfunnel - JP": "10. Funnels imported from clickfunnel - JP",
    "2. Incorporación de Marketing Solution Plus Support Portal 2.0 - JP": "2. Marketing Solution Plus Support Portal 2.0 Onboarding - JP",
    "3. Instantánea de bienes raíces en inglés - JP": "3. English Real State Snapshot - JP",
    "¡Ups! No se encontraron elementos. Considere cambiar la consulta de búsqueda.": "Oops! No elements found. Consider changing the search query.",
    "La lista esta vacía.": "List is empty.",
    "Seleccione hasta 3 ubicaciones": "Select upto 3 locations",
    "La clonación está limitada a 3 ubicaciones a la vez": "Cloning is limited to 3 locations at a time",
    "¿Eliminar elemento seleccionado?": "Delete selected item?",
    "Esta acción no se puede revertir.": "This action cannot be reversed.",
    "El elemento seleccionado se eliminará permanentemente de su cuenta.": "The selected item will be permanently deleted from your account.",
    "Confirme la eliminación escribiendo &#39;ELIMINAR&#39; a continuación:": "Confirm deletion by typing 'DELETE' below:",
    "Cancelar, Mantener": "Cancel, Keep",
    "Sí, Eliminar": "Yes, Delete",
    "Carpeta": "Folder",
    "Mover a la carpeta seleccionada": "Move to Selected Folder",
    "Embudos de búsqueda": "Search Funnels",
    "Nombre para su increíble embudo": "Name for your awesome Funnel",
    "Introduzca un nuevo nombre para la carpeta": "Enter new name for folder",
    "Nombre para tu carpeta": "Name for your folder"
}

var lan = 'en';

function addElem(){
    const header = document.querySelector(".hl_header--controls");
    if(header == null){
        setTimeout(addElem, 500);
    }else {
        const langs = {
            'English': 'en',
            'Spanish': 'es'/*,
            'French': 'fr',
            'German': 'de',
            'Italian': 'it',
            'Portuguese': 'pt',
            'Russian': 'ru',
            'Japanese': 'ja',
            'Korean': 'ko',
            'Dutch': 'nl',
            'Swedish': 'sv'*/
        }
        var link = document.createElement("link");
        link.rel = "stylesheet";
        link.href = 'https://ghltranslator.onrender.com/trnscss.css';
        document.head.appendChild(link);
        const button = document.createElement("button");
        button.classList = 'trnsbtn';
        button.innerText = lan.toUpperCase();
        header.insertBefore(button, header.childNodes[1]);
        var translate = 'translate(5vh, 0)';
        if(header.offsetWidth < header.offsetHeight){
            button.classList.add('h');
            translate = 'translate(50% , 12vw)';
        }
        button.addEventListener('click', ()=>{
            const langlist = document.createElement('div');
            langlist.style.transform = translate;
            langlist.classList = 'translatorList';
            for(const lang in langs){
                if(langs[lang] != lan){
                    let btt = document.createElement("div");
                    btt.innerText = lang + ' ('+langs[lang]+')';
                    btt.addEventListener('click', (event)=>{
                        event.stopPropagation();
                        lan = langs[lang];
                        button.innerText = lan.toUpperCase();
                        translate();
                    });
                    langlist.appendChild(btt);
                }
            }
            button.appendChild(langlist);
        });
    }
}

function translate(){
    var walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, null, false);
    while (walker.nextNode()) {
        let node = walker.currentNode;
        const pat = /[@]/g;
        const pat2 = /[a-zA-Z]/g;
        let text = node.nodeValue.trim();
        if(text != '' && !hasClassAncestor(node.parentNode) && (lan == 'es' ? !txtDicInv[text] : !txtDic[text]) && !text.match(pat) && text.match(pat2)){
            if(!txtDic[text] && !txtDicInv[text] && node.parentNode.nodeName != ('STYLE' || 'SCRIPT')){
                console.log('Missing "' + text + '" from dictionary');
            }else{
                node.nodeValue = (lan == 'es' ? txtDic[text] : txtDicInv[text]);
            }
        }
    }
    
    const inputs = document.getElementsByTagName('input');
    for (let i = 0; i < inputs.length; i++) {
        let oldP = inputs[i].getAttribute('placeholder');
        if( !txtDic[oldP] && !txtDicInv[oldP]){
            console.log('Missing "' + oldP + '" from dictionary')
        }else{
            inputs[i].setAttribute('placeholder', lan == 'es' ? txtDic[oldP] : txtDicInv[oldP]);
        }
    }

    lan != 'en' ? setTimeout(translate, 1000) : null;
}

function hasClassAncestor(elem){
    while (elem) {
    if (elem.classList && (elem.classList.contains('email-group') || elem.classList.contains('messages-list--item-v2'))) {
      return true;
    }
    elem = elem.parentNode;
  }
  return false;
}

addElem()